### ISSUE TITLE
Support for Django 3

### ISSUE THREAD

**Issue by ajenhl** [kingsdigitallab/django-controlled-vocabulary#13]
Currently this package on PyPI (v0.9) is restricted to django<3.0,>=2.2. Unless there is some code incompatability with Django 3, could this specification be changed please?

**Comment by geoffroy-noel-ddh** [comment]
I'll have a look at it this week. Let me know if it's urgent and I'll try to prioritise. Feel free to contribute if you wish (and have time).

**Comment by geoffroy-noel-ddh** [comment]
@ajenhl I've just released a new version 0.10 with support for Django 2.2 to 3.1.

I didn't touch the code at all. I've only done some quick manual tests and adapted travis/tox to run unit tests on Django 3.1 and all looked ok but let me know if you notice any problem.

**Comment by ajenhl** [comment]
Thanks; I am literally just about to make first use of this under Django 3.1!
