### ISSUE TITLE
Search by term id as well as label in external dataset

### ISSUE THREAD

**Issue by ajenhl** [kingsdigitallab/django-controlled-vocabulary#8]
I need to be able to look up languages by language code (via search_term_or_none). Currently the vocabularies/base_list.py search method only searches on the label and not the term id, making this impossible.

**Comment by geoffroy-noel-ddh** [comment]
I think the search_term_or_none() looks up both the termid and the label (although the docstring doesn't explain that!).

```python
>>> utils.search_term_or_none('iso639-2', 'Manx')
<ControlledTerm: Manx (iso639-2)>
>>> utils.search_term_or_none('iso639-2', 'glv')
<ControlledTerm: Manx (iso639-2)>
>>> utils.search_term_or_none('iso639-2', 'glv').termid
'glv'
```

Is that what you want? If not show me an example that doesn't work and I'll see what I can do.

**Comment by geoffroy-noel-ddh** [comment]
Ok, my mistake, that's obviously because my first call above adds the term in the table, so the second call on the termid works.

I see. I'll add that functionality. That won't be possible for remote vocs but the local ones like base_list or CSV are possible.

**Comment by geoffroy-noel-ddh** [comment]
search_term_or_none() should now work well with a termid as a pattern.

e.g.
utils.search_term_or_none('iso639-2', 'glv').termid
=> 'glv'

Also added unit tests to cover those new cases.

See gh-10 for details about resolution and about iso639-2 treatment of Bibliograpic vs Terminology.

**Comment by geoffroy-noel-ddh** [comment]
Closing for now, but let me know if you notice any problem.
