### ISSUE TITLE
Provide sample migration for running vocab init

### ISSUE THREAD

**Issue by ajenhl** [kingsdigitallab/django-controlled-vocabulary#9]
Automatic deployment, such as through fab, that involves data migration to controlled vocabulary models requires the vocab to be init before the data migration. It would be useful to provide in the docs a sample migration that runs the `vocab init` management command, for users to base their own off.

**Comment by geoffroy-noel-ddh** [comment]
I've started working on 'init-on-demand' rather than manual init. Missing external vocabuary files are now downloaded automatically the first time a look up is done. I just need to make make a lazy update of the voc definitions in the DB and hopefully that a manual init will no longer be needed.

**Comment by geoffroy-noel-ddh** [comment]
New version 0.8 should be more migration friendly now.

https://github.com/kingsdigitallab/django-controlled-vocabulary/blob/master/CHANGELOG.md

**Comment by jmiguelv** [comment]
I still have issues with data migrations that use controlled terms using version 0.8 and `search_term_or_none`.

**Comment by ajenhl** [comment]
Interesting; a deployment that installed it and performed a complex data migration apparently worked just now.

**Comment by jmiguelv** [comment]
Hmmm, this is happening when I run tests locally.

**Comment by jmiguelv** [comment]
No, it was my issue, sorry. I had a local version of the app that was still at version 0.6, 0.8 is working as expected.
